### ISSUE TITLE
Getting protocol packets from serial stream

### ISSUE THREAD

**Issue by cmcqueen** [j123b567/SerialPCAP#2]
This tool captures chunks of serial data and saves them in pcap "frames", but those chunks don't necessarily correspond to packets of the underlying protocol. Wireshark has limitations on its ability for custom dissectors to reassemble packets from data that spans 2 or more pcap frames.

Since you developed this tool apparently for capturing Modbus-RTU, how do you dissect (in Wireshark) individual Modbus-RTU packets from the serial data chunks in the pcap file, with packet reassembly as required?

**Comment by j123b567** [comment]
You must use correct inter-frame-gap configuration.

I'm using this tool to discover also wrong framing on custom devices.
I have also tool to reassamble one pcap file to another with known protocol (currently, only modbus-rtu) so I can view all (also probably corrupted) packets in wireshark.

I can publish this tool also.

**Comment by cmcqueen** [comment]
That makes sense. Thanks for explaining. In my case I have a protocol which may not have a timing gap between frames.

I'll probably end up making a custom serial capture program for my protocol, that detects packet boundaries, and writes a pcap file with each packet in a pcap frame. Then I can also make it to take input from a generic pcap file and do the same, outputting a correctly framed pcap file.

**Comment by cmcqueen** [comment]
I don't care about Modbus-RTU myself, but I'm sure there would be others who would be interested to see your tool for reprocessing pcap files.

**Comment by j123b567** [comment]
Just in case, here is my example of modbus-rtu reassable https://gist.github.com/j123b567/37153ba4d3a365cdfbce076e38ffd14d

**Comment by cmcqueen** [comment]
Thanks for sharing your code.
